=== diepnt03/TTHTPM/b4/NguyenThiDiep_2021601120_HTTT01/thuchanh/build/classes/thuchanh/Class.xsd
<?xml version="1.0"?>


<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
<xs:complexType name ="person">
	<xs:sequence>
		<xs:element name="sid">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[S]\d{3}"/> 
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="name">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[A-Za-z ]+"/>	
				</xs:restriction>						
			</xs:simpleType>
		</xs:element>
		<xs:element name="dob" type="xs:date"/>
		<xs:element name="mark">	<!--mark là số chỉ cho phép từ 1 đến 10-->
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="1"/>
					<xs:maxInclusive value="10"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:sequence>
</xs:complexType>
<xs:element name="class">
	<xs:complexType>
		<xs:sequence>
			<!-- sẽ có ít nhất 1 con student, nhiều nhất là vo hạn-->
			<xs:element name="student" type="person" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== diepnt03/TTHTPM/b4/NguyenThiDiep_2021601120_HTTT01/thuchanh/build/classes/thuchanh/Class.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<class
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Class.xsd'>
    <student>
        <sid>S098</sid>
        <name>Van Anh</name>
        <dob>1996-12-25</dob>
        <mark>9</mark>
    </student>
    <student>
        <sid>S123</sid>
        <name></name>
        <dob></dob>
        <mark></mark>
    </student>
    <student>
        <sid></sid>
        <name></name>
        <dob></dob>
        <mark></mark>
    </student>

</class>
